In [1]:
import pandas as pd

In [2]:
!wget https://raw.githubusercontent.com/iaportnov/GP_2_real_estate_investment_strategy/refs/heads/main/sale_trends_data_frame.csv

--2026-04-09 15:11:22--  https://raw.githubusercontent.com/iaportnov/GP_2_real_estate_investment_strategy/refs/heads/main/sale_trends_data_frame.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4071990 (3.9M) [text/plain]
Saving to: ‘sale_trends_data_frame.csv’

sale_trends_data_fr 100%[===================>]   3.88M  --.-KB/s    in 0.07s

2026-04-09 15:11:23 (56.2 MB/s) - ‘sale_trends_data_frame.csv’ saved [4071990/4071990]

In [26]:
sale_trends_df = pd.read_csv('sale_trends_data_frame.csv', index_col = 0)

In [27]:
sale_trends_df = sale_trends_df.fillna(0)

In [39]:
sale_trends_df['avg_homeSaleCount'] = ((sale_trends_df['homeSaleCount_2020']
                                        + sale_trends_df['homeSaleCount_2021']
                                        + sale_trends_df['homeSaleCount_2022']
                                        + sale_trends_df['homeSaleCount_2023']
                                        + sale_trends_df['homeSaleCount_2024']
                                        + sale_trends_df['homeSaleCount_2025'])/5).round(2)
sale_trends_df['avg_medSalePrice'] = ((sale_trends_df['medSalePrice_2020']
                                        + sale_trends_df['medSalePrice_2021']
                                        + sale_trends_df['medSalePrice_2022']
                                        + sale_trends_df['medSalePrice_2023']
                                        + sale_trends_df['medSalePrice_2024']
                                        + sale_trends_df['medSalePrice_2025'])/5).round(2)

In [46]:
sale_trends_df['avg_homeSaleCount'].quantile(0.75)

np.float64(70.6)

In [41]:
sale_trends_df.sort_values('avgSalePrice_2025')

,geo_id,homeSaleCount_2020,avgSalePrice_2020,medSalePrice_2020,homeSaleCount_2021,avgSalePrice_2021,medSalePrice_2021,homeSaleCount_2022,avgSalePrice_2022,medSalePrice_2022,...,avgSalePrice_2023,medSalePrice_2023,homeSaleCount_2024,avgSalePrice_2024,medSalePrice_2024,homeSaleCount_2025,avgSalePrice_2025,medSalePrice_2025,avg_homeSaleCount,avg_medSalePrice
2475,1c8da77f30d59fb49623590a2e602292,53.0,806926.0,550000.0,48.0,1110843.0,775000.0,34.0,1214294.0,854000.0,...,0.0,0.0,3.0,4466666.0,4500000.0,0.0,0.0,0.0,27.6,1335800.0
20446,14a4d625a5ecf6855e1d79c4d793717e,0.0,0.0,0.0,2.0,353281.0,353281.0,0.0,0.0,0.0,...,352625.0,352625.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8,141181.2
2427,8ef4e598a9f597f86831c8071a61236c,6.0,511333.0,502500.0,5.0,662500.0,350000.0,4.0,1381591.0,1403182.0,...,1025750.0,476500.0,0.0,0.0,0.0,0.0,0.0,0.0,3.8,546436.4
2426,a218fa3a4b283994dc97e0d3a6a688c9,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2566666.0,2500000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,500000.0
20468,e0e9d7a6640d5c1f92ab125a34574584,0.0,0.0,0.0,0.0,0.0,0.0,2.0,309237.0,309237.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,61847.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2169,a891b33f3890dc191decc2f1cd63489b,20.0,5467875.0,5492500.0,37.0,5988729.0,5800000.0,21.0,7018690.0,7500000.0,...,7668350.0,7740000.0,6.0,8391666.0,8840000.0,9.0,7421722.0,7300000.0,20.6,8534500.0
19495,834c1a09b23d32b9b544cf3ddfab4827,4.0,630000.0,482500.0,3.0,2179166.0,1250000.0,2.0,412000.0,412000.0,...,445000.0,390000.0,3.0,495467.0,443500.0,2.0,8099179.0,8099179.0,3.8,2215435.8
6209,98507151a7d856b00e5a823dcfa03f72,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5190000.0,5200000.0,5.0,4815000.0,3950000.0,4.0,8285000.0,8307500.0,2.8,3491500.0
1808,5fd843a157a513711af5e035ea9ef538,9.0,4250000.0,5065000.0,8.0,7005000.0,7200000.0,9.0,4299444.0,4000000.0,...,5350000.0,6000000.0,2.0,4117500.0,4117500.0,2.0,8375000.0,8375000.0,6.8,6951500.0
1866,d8cedbe8944ad6178859207604904f4d,3.0,6589666.0,7600000.0,3.0,3806000.0,2650000.0,4.0,3939625.0,4250000.0,...,0.0,0.0,0.0,0.0,0.0,2.0,8450000.0,8450000.0,2.4,4590000.0

In [47]:
sale_trends_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24462 entries, 0 to 24461
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   geo_id              24462 non-null  object
 1   homeSaleCount_2020  24462 non-null  float64
 2   avgSalePrice_2020   24462 non-null  float64
 3   medSalePrice_2020   24462 non-null  float64
 4   homeSaleCount_2021  24462 non-null  float64
 5   avgSalePrice_2021   24462 non-null  float64
 6   medSalePrice_2021   24462 non-null  float64
 7   homeSaleCount_2022  24462 non-null  float64
 8   avgSalePrice_2022   24462 non-null  float64
 9   medSalePrice_2022   24462 non-null  float64
 10  homeSaleCount_2023  24462 non-null  float64
 11  avgSalePrice_2023   24462 non-null  float64
 12  medSalePrice_2023   24462 non-null  float64
 13  homeSaleCount_2024  24462 non-null  float64
 14  avgSalePrice_2024   24462 non-null  float64
 15  medSalePrice_2024   24462 non-null  float64
 16  homeSaleCount_2025  24462 non-null  float64
 17  avgSalePrice_2025   24462 non-null  float64
 18  medSalePrice_2025   24462 non-null  float64
 19  avg_homeSaleCount   24462 non-null  float64
 20  avg_medSalePrice    24462 non-null  float64
dtypes: float64(20), object(1)
memory usage: 4.1+ MB

In [76]:
df_clean = sale_trends_df[(sale_trends_df['homeSaleCount_2022'] >= 10) & (sale_trends_df['homeSaleCount_2025'] >= 10)].copy()

In [77]:
df_clean['cagr_med_price'] = (((df_clean['medSalePrice_2025'] / df_clean['medSalePrice_2022']) ** (1/3) - 1) * 100).round(4)
df_clean['cagr_sale_count'] = (((df_clean['homeSaleCount_2025'] / df_clean['homeSaleCount_2022']) ** (1/3) - 1) * 100).round(4)

In [81]:
df_clean = df_clean[df_clean['cagr_med_price']>4.4].sort_values('cagr_med_price', ascending = False)

In [85]:
q90 = df_clean['avg_medSalePrice'].quantile(0.9)
q10 = df_clean['avg_medSalePrice'].quantile(0.1)
df_clean = df_clean[(df_clean['avg_medSalePrice'] > q10) & (df_clean['avg_medSalePrice'] < q90)]

In [88]:
sale_trends_df_clean = df_clean[['geo_id','medSalePrice_2025', 'homeSaleCount_2025', 'cagr_med_price', 'cagr_sale_count']]

In [89]:
sale_trends_df_clean

,geo_id,medSalePrice_2025,homeSaleCount_2025,cagr_med_price,cagr_sale_count
5415,9cd7eab982c5c35bcd6f05d732d333c5,310000.0,21.0,113.2866,28.0579
5369,b508f5dc4143a48154f0ff995b081678,1215000.0,16.0,94.5498,13.3033
136,5b55d57472de1efb82e58cc003f53b78,487000.0,14.0,93.7097,-29.5270
13406,6a62dc1d0f1a59ae0c3de95037e1b683,323800.0,18.0,91.6489,14.4714
19553,d7926013088462e0208e1edce50bf340,1756090.0,11.0,89.0273,-5.4163
...,...,...,...,...,...
5122,d1e3095ab678803f4b041f4235798872,413500.0,32.0,4.4087,-20.2122
19167,50ebe9038c385b6117d18e557d076841,239000.0,17.0,4.4062,-22.8358
12693,3c969346ea2aa69d1b17362ecb262c76,400000.0,73.0,4.4027,-2.1841
8867,a6498e25964d71c4c3834d3f9c4bb11a,660000.0,22.0,4.4012,-7.7241
18129,748b3444fcd67399ce7da7b6fd003935,320437.0,48.0,4.4006,-12.6420

In [90]:
sale_trends_df_clean.to_csv('sale_trends_df_clean.csv')