In [11]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
import time
import pandas as pd
import warnings
import numpy as np
import logging
from tqdm import tqdm
from datetime import datetime

warnings.filterwarnings('ignore')
df = pd.read_csv('area_sales_community_df.csv', index_col=0)

In [12]:
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[logging.FileHandler(f'scraper_{datetime.now().strftime("%Y%m%d_%H%M%S")}.log'), logging.StreamHandler()])
logger = logging.getLogger(__name__)

In [13]:
def get_geography_names(geography_name):
  all_names = geography_name.split(',')
  if len(all_names) == 3:
    return np.nan
  return ', '.join(all_names[:2])

df_pars = df[['geo_id', 'geographyName']]
df_pars[['neighborhood_city']] = df_pars['geographyName'].apply(lambda x: pd.Series(get_geography_names(x)))
df_pars = df_pars.drop('geographyName', axis=1)
df_pars['links'] = pd.Series()
df_pars = df_pars[~df_pars['neighborhood_city'].isna()].reset_index(drop=True)
df_pars

                                geo_id                neighborhood_city links
0     9cd7eab982c5c35bcd6f05d732d333c5           Price End,  North Port   NaN
1     b508f5dc4143a48154f0ff995b081678        The Hills,  Coral Springs   NaN
2     5b55d57472de1efb82e58cc003f53b78  Whitesburg Estates,  Huntsville   NaN
3     6a62dc1d0f1a59ae0c3de95037e1b683               Kittyhawk,  Dayton   NaN
4     8f3ec7cc1c199a0a566221bee1aeaa9c    New Hampstead East,  Savannah   NaN
...                                ...                              ...   ...
4207  d1e3095ab678803f4b041f4235798872               Flair,  Lauderhill   NaN
4208  50ebe9038c385b6117d18e557d076841            Lake Bonny,  Lakeland   NaN
4209  3c969346ea2aa69d1b17362ecb262c76      Bronx Park,  St. Louis Park   NaN
4210  a6498e25964d71c4c3834d3f9c4bb11a            Livingston,  New York   NaN
4211  748b3444fcd67399ce7da7b6fd003935           College Hill,  Wichita   NaN

[4212 rows x 3 columns]

In [16]:
options = Options()
driver = webdriver.Chrome(options=options)
url = 'https://www.greatschools.org/school-district-boundaries-map/'
driver.get(url)
driver.find_element(By.CSS_SELECTOR, '#privacy-banner-close').click()
driver.find_element(By.CSS_SELECTOR, '#cmpwrapper').shadow_root.find_element(By.CSS_SELECTOR, '#cmpwelcomebtnyes').click()

element = driver.find_element(By.CSS_SELECTOR, '[id^="ConnectedDistrictBoundaries-react-component"]')
id = element.get_attribute('id')

inp = driver.find_element(By.XPATH, f'//*[@id="{id}"]/div/div/div[1]/div[1]/div[1]/div[1]/input')
inp.clear()
inp.send_keys('Price End, North Port')
driver.find_element(By.XPATH, f'//*[@id="{id}"]/div/div/div[1]/div[1]/div[1]/div[2]').click()
WebDriverWait(driver, 60).until(EC.element_to_be_clickable((By.XPATH, f'//*[@id="{id}"]/div/div/div[2]/div[1]/div[3]/div[1]')))
driver.find_element(By.XPATH, f'//*[@id="{id}"]/div/div/div[2]/div[1]/div[3]/div[1]').click()
driver.find_element(By.XPATH, '/html/body/div[16]/div/div/div[2]/div[1]/div/div/div/div[2]/div/section/ul/div[2]/span/input').click()
driver.find_element(By.XPATH, '/html/body/div[16]/div/div/div[2]/div[2]/div/button').click()

In [32]:
def get_links(x):
    try:
        a = soup.find_all('div', class_='primary-section')[0].find_all('div', class_='header')
        ans = []
        if len(a) > 3:
            a = a[:3]
        for i in a:
            link = i.find_all('a', class_='name')[0]['href']
            ans.append(f'https://www.greatschools.org/{link}')
        return ans
    except:
        return np.nan

for i in df_pars[2275:].iterrows():
    logger.info(f'Парсинг района: {i[1]['neighborhood_city']}')
    inp = driver.find_element(By.XPATH, f'//*[@id="{id}"]/div/div/div[2]/div[1]/div[2]/div[1]/input')
    inp.clear()
    inp.send_keys(i[1]['neighborhood_city'])
    driver.find_element(By.XPATH, f'//*[@id="{id}"]/div/div/div[2]/div[1]/div[2]/div[2]').click()
    try:
        WebDriverWait(driver, 2).until(EC.alert_is_present())
        driver.switch_to.alert.accept()
        logger.warning(f'Район не найден: {i[1]['neighborhood_city']}')
    except:
        WebDriverWait(driver, 10).until(EC.invisibility_of_element_located((By.CSS_SELECTOR, '.spinny-wheel')))
        driver.find_element(By.XPATH, f'//*[@id="{id}"]/div/div/div[2]/div[1]/div[1]/div[1]').click()
        driver.find_element(By.CSS_SELECTOR, f'#{id} > div > div > div.primary-section > div.controls-section > div.filter-bar > div.sort-options > div > div > div > div > div').click()
        driver.find_element(By.CSS_SELECTOR, f'#{id} > div > div > div.primary-section > div.controls-section > div.filter-bar > div.sort-options > div > div > div > ul > li:nth-child(2)').click()
        WebDriverWait(driver, 10).until(EC.invisibility_of_element_located((By.CSS_SELECTOR, '.spinny-wheel')))
    
        page_source = driver.page_source
        soup = BeautifulSoup(page_source, 'html.parser')
        links = get_links(soup)
        df_pars['links'].iloc[i[0]] = links
        logger.info(f'Для района {i[1]['neighborhood_city']} получено {len(links) if links != np.nan else 0} ссылок на школы')
        logger.info(f'Прогресс - {i[0]}/{len(df_pars)}')

logger.info('КОНЕЦ')

2026-04-10 04:49:12,638 - INFO - Парсинг района: Port Jefferson Station,  Port Jefferson Station
2026-04-10 04:49:15,832 - INFO - Для района Port Jefferson Station,  Port Jefferson Station получено 3 ссылок на школы
2026-04-10 04:49:15,833 - INFO - Прогресс - 2275/4212
2026-04-10 04:49:15,834 - INFO - Парсинг района: Randall Manor,  New York
2026-04-10 04:49:18,967 - INFO - Для района Randall Manor,  New York получено 3 ссылок на школы
2026-04-10 04:49:18,968 - INFO - Прогресс - 2276/4212
2026-04-10 04:49:18,969 - INFO - Парсинг района: East Little York / Homestead,  Houston
2026-04-10 04:49:22,023 - INFO - Для района East Little York / Homestead,  Houston получено 3 ссылок на школы
2026-04-10 04:49:22,024 - INFO - Прогресс - 2277/4212
2026-04-10 04:49:22,025 - INFO - Парсинг района: Hunters Creek,  Hunters Creek
2026-04-10 04:49:25,169 - INFO - Для района Hunters Creek,  Hunters Creek получено 3 ссылок на школы
2026-04-10 04:49:25,170 - INFO - Прогресс - 2278/4212
2026-04-10 04:49:25,171 - INFO - Парсинг района: Ballantyne West,  Charlotte
2026-04-10 04:49:28,275 - INFO - Для района Ballantyne West,  Charlotte получено 3 ссылок на школы
2026-04-10 04:49:28,276 - INFO - Прогресс - 2279/4212
2026-04-10 04:49:28,277 - INFO - Парсинг района: Arlingwood,  Jacksonville
2026-04-10 04:49:31,709 - INFO - Для района Arlingwood,  Jacksonville получено 3 ссылок на школы
2026-04-10 04:49:31,710 - INFO - Прогресс - 2280/4212
2026-04-10 04:49:31,711 - INFO - Парсинг района: West End Park,  Nashville-Davidson metropolitan government (balance)
2026-04-10 04:49:34,917 - INFO - Для района West End Park,  Nashville-Davidson metropolitan government (balance) получено 3 ссылок на школы
2026-04-10 04:49:34,918 - INFO - Прогресс - 2281/4212
2026-04-10 04:49:34,919 - INFO - Парсинг района: Ardmore Park,  Greensboro
2026-04-10 04:49:38,182 - INFO - Для района Ardmore Park,  Greensboro получено 3 ссылок на школы
2026-04-10 04:49:38,183 - INFO - Прогресс - 2282/4212
2026-04-10 04:49:38,184 - INFO - Парсинг района: Zilker,  Austin
2026-04-10 04:49:41,225 - INFO - Для района Zilker,  Austin получено 3 ссылок на школы
2026-04-10 04:49:41,226 - INFO - Прогресс - 2283/4212
2026-04-10 04:49:41,227 - INFO - Парсинг района: Beech Grove,  Beech Grove
2026-04-10 04:49:44,240 - INFO - Для района Beech Grove,  Beech Grove получено 3 ссылок на школы
2026-04-10 04:49:44,242 - INFO - Прогресс - 2284/4212
2026-04-10 04:49:44,242 - INFO - Парсинг района: Whitehall,  Albany
2026-04-10 04:49:47,272 - INFO - Для района Whitehall,  Albany получено 3 ссылок на школы
2026-04-10 04:49:47,273 - INFO - Прогресс - 2285/4212
2026-04-10 04:49:47,275 - INFO - Парсинг района: Plainedge,  Plainedge
2026-04-10 04:49:50,288 - INFO - Для района Plainedge,  Plainedge получено 3 ссылок на школы
2026-04-10 04:49:50,289 - INFO - Прогресс - 2286/4212
2026-04-10 04:49:50,290 - INFO - Парсинг района: Country Grove,  Dunedin
2026-04-10 04:49:53,361 - INFO - Для района Country Grove,  Dunedin получено 3 ссылок на школы
2026-04-10 04:49:53,362 - INFO - Прогресс - 2287/4212
2026-04-10 04:49:53,363 - INFO - Парсинг района: Grant Wood,  Iowa City
2026-04-10 04:49:56,553 - INFO - Для района Grant Wood,  Iowa City получено 3 ссылок на школы
2026-04-10 04:49:56,555 - INFO - Прогресс - 2288/4212
2026-04-10 04:49:56,556 - INFO - Парсинг района: Bowman,  Louisville
2026-04-10 04:49:59,595 - INFO - Для района Bowman,  Louisville получено 3 ссылок на школы
2026-04-10 04:49:59,596 - INFO - Прогресс - 2289/4212
2026-04-10 04:49:59,597 - INFO - Парсинг района: Northside,  Ann Arbor
2026-04-10 04:50:02,650 - INFO - Для района Northside,  Ann Arbor получено 3 ссылок на школы
2026-04-10 04:50:02,651 - INFO - Прогресс - 2290/4212
2026-04-10 04:50:02,652 - INFO - Парсинг района: Hialeah,  Hialeah
2026-04-10 04:50:05,715 - INFO - Для района Hialeah,  Hialeah получено 3 ссылок на школы
2026-04-10 04:50:05,716 - INFO - Прогресс - 2291/4212
2026-04-10 04:50:05,716 - INFO - Парсинг района: Levagood,  Dearborn
2026-04-10 04:50:08,784 - INFO - Для района Levagood,  Dearborn получено 3 ссылок на школы
2026-04-10 04:50:08,785 - INFO - Прогресс - 2292/4212
2026-04-10 04:50:08,786 - INFO - Парсинг района: Westlake / Prairieview,  Battle Creek
2026-04-10 04:50:11,866 - INFO - Для района Westlake / Prairieview,  Battle Creek получено 3 ссылок на школы
2026-04-10 04:50:11,867 - INFO - Прогресс - 2293/4212
2026-04-10 04:50:11,868 - INFO - Парсинг района: Rockfish,  Rockfish
2026-04-10 04:50:14,895 - INFO - Для района Rockfish,  Rockfish получено 3 ссылок на школы
2026-04-10 04:50:14,896 - INFO - Прогресс - 2294/4212
2026-04-10 04:50:14,897 - INFO - Парсинг района: Manton,  Providence
2026-04-10 04:50:17,988 - INFO - Для района Manton,  Providence получено 3 ссылок на школы
2026-04-10 04:50:17,989 - INFO - Прогресс - 2295/4212
2026-04-10 04:50:17,991 - INFO - Парсинг района: Islip Terrace,  Islip Terrace
2026-04-10 04:50:21,036 - INFO - Для района Islip Terrace,  Islip Terrace получено 3 ссылок на школы
2026-04-10 04:50:21,037 - INFO - Прогресс - 2296/4212
2026-04-10 04:50:21,039 - INFO - Парсинг района: Naylor,  Tucson
2026-04-10 04:50:24,057 - INFO - Для района Naylor,  Tucson получено 3 ссылок на школы
2026-04-10 04:50:24,058 - INFO - Прогресс - 2297/4212
2026-04-10 04:50:24,059 - INFO - Парсинг района: Rice Creek North Park,  Shoreview
2026-04-10 04:50:27,183 - INFO - Для района Rice Creek North Park,  Shoreview получено 3 ссылок на школы
2026-04-10 04:50:27,184 - INFO - Прогресс - 2298/4212
2026-04-10 04:50:27,185 - INFO - Парсинг района: Copiague,  Copiague
2026-04-10 04:50:30,232 - INFO - Для района Copiague,  Copiague получено 3 ссылок на школы
2026-04-10 04:50:30,233 - INFO - Прогресс - 2299/4212
2026-04-10 04:50:30,234 - INFO - Парсинг района: Boulevard Gardens,  Denver
2026-04-10 04:50:33,278 - INFO - Для района Boulevard Gardens,  Denver получено 3 ссылок на школы
2026-04-10 04:50:33,279 - INFO - Прогресс - 2300/4212
2026-04-10 04:50:33,280 - INFO - Парсинг района: Flagstaff Townsite,  Flagstaff
2026-04-10 04:50:36,355 - INFO - Для района Flagstaff Townsite,  Flagstaff получено 3 ссылок на школы
2026-04-10 04:50:36,356 - INFO - Прогресс - 2301/4212
2026-04-10 04:50:36,356 - INFO - Парсинг района: White Ash,  Columbus
2026-04-10 04:50:39,413 - INFO - Для района White Ash,  Columbus получено 3 ссылок на школы
2026-04-10 04:50:39,414 - INFO - Прогресс - 2302/4212
2026-04-10 04:50:39,415 - INFO - Парсинг района: Palomar Townhomes,  Lexington-Fayette
2026-04-10 04:50:42,522 - INFO - Для района Palomar Townhomes,  Lexington-Fayette получено 3 ссылок на школы
2026-04-10 04:50:42,523 - INFO - Прогресс - 2303/4212
2026-04-10 04:50:42,523 - INFO - Парсинг района: Dogwood Trace,  Lexington-Fayette
2026-04-10 04:50:45,648 - INFO - Для района Dogwood Trace,  Lexington-Fayette получено 3 ссылок на школы
2026-04-10 04:50:45,649 - INFO - Прогресс - 2304/4212
2026-04-10 04:50:45,650 - INFO - Парсинг района: Mount Airy,  Cincinnati
2026-04-10 04:50:48,707 - INFO - Для района Mount Airy,  Cincinnati получено 3 ссылок на школы
2026-04-10 04:50:48,708 - INFO - Прогресс - 2305/4212
2026-04-10 04:50:48,709 - INFO - Парсинг района: Forty Acres,  Wilmington
2026-04-10 04:50:51,770 - INFO - Для района Forty Acres,  Wilmington получено 3 ссылок на школы
2026-04-10 04:50:51,771 - INFO - Прогресс - 2306/4212
2026-04-10 04:50:51,772 - INFO - Парсинг района: Southwest Waterfront / Fort McNair / Buzzard Point,  Washington
2026-04-10 04:50:54,868 - INFO - Для района Southwest Waterfront / Fort McNair / Buzzard Point,  Washington получено 3 ссылок на школы
2026-04-10 04:50:54,869 - INFO - Прогресс - 2307/4212
2026-04-10 04:50:54,871 - INFO - Парсинг района: Newton Square,  Worcester
2026-04-10 04:50:57,916 - INFO - Для района Newton Square,  Worcester получено 3 ссылок на школы
2026-04-10 04:50:57,917 - INFO - Прогресс - 2308/4212
2026-04-10 04:50:57,918 - INFO - Парсинг района: Liberty Park,  Pompano Beach
2026-04-10 04:51:01,009 - INFO - Для района Liberty Park,  Pompano Beach получено 3 ссылок на школы
2026-04-10 04:51:01,010 - INFO - Прогресс - 2309/4212
2026-04-10 04:51:01,011 - INFO - Парсинг района: Spring Park Bay,  Mound
2026-04-10 04:51:04,415 - INFO - Для района Spring Park Bay,  Mound получено 3 ссылок на школы
2026-04-10 04:51:04,416 - INFO - Прогресс - 2310/4212
2026-04-10 04:51:04,417 - INFO - Парсинг района: Decatur Heights,  Decatur
2026-04-10 04:51:07,696 - INFO - Для района Decatur Heights,  Decatur получено 3 ссылок на школы
2026-04-10 04:51:07,698 - INFO - Прогресс - 2311/4212
2026-04-10 04:51:07,699 - INFO - Парсинг района: Liberty Heights,  Springfield
2026-04-10 04:51:10,847 - INFO - Для района Liberty Heights,  Springfield получено 3 ссылок на школы
2026-04-10 04:51:10,849 - INFO - Прогресс - 2312/4212
2026-04-10 04:51:10,850 - INFO - Парсинг района: Lyons Park,  Milwaukee
2026-04-10 04:51:14,107 - INFO - Для района Lyons Park,  Milwaukee получено 3 ссылок на школы
2026-04-10 04:51:14,108 - INFO - Прогресс - 2313/4212
2026-04-10 04:51:14,109 - INFO - Парсинг района: Wyandotte,  Louisville
2026-04-10 04:51:17,195 - INFO - Для района Wyandotte,  Louisville получено 3 ссылок на школы
2026-04-10 04:51:17,196 - INFO - Прогресс - 2314/4212
2026-04-10 04:51:17,197 - INFO - Парсинг района: Old South Baton Rouge,  Baton Rouge
2026-04-10 04:51:21,346 - INFO - Для района Old South Baton Rouge,  Baton Rouge получено 3 ссылок на школы
2026-04-10 04:51:21,347 - INFO - Прогресс - 2315/4212
2026-04-10 04:51:21,348 - INFO - Парсинг района: Carlton,  Muncie
2026-04-10 04:51:24,369 - INFO - Для района Carlton,  Muncie получено 3 ссылок на школы
2026-04-10 04:51:24,370 - INFO - Прогресс - 2316/4212
2026-04-10 04:51:24,371 - INFO - Парсинг района: Better Waverly,  Baltimore
2026-04-10 04:51:27,487 - INFO - Для района Better Waverly,  Baltimore получено 3 ссылок на школы
2026-04-10 04:51:27,488 - INFO - Прогресс - 2317/4212
2026-04-10 04:51:27,489 - INFO - Парсинг района: Huntington,  Fresno
2026-04-10 04:51:30,538 - INFO - Для района Huntington,  Fresno получено 3 ссылок на школы
2026-04-10 04:51:30,539 - INFO - Прогресс - 2318/4212
2026-04-10 04:51:30,540 - INFO - Парсинг района: Commanche,  Lafayette
2026-04-10 04:51:33,581 - INFO - Для района Commanche,  Lafayette получено 3 ссылок на школы
2026-04-10 04:51:33,582 - INFO - Прогресс - 2319/4212
2026-04-10 04:51:33,583 - INFO - Парсинг района: Uniondale,  Uniondale
2026-04-10 04:51:36,656 - INFO - Для района Uniondale,  Uniondale получено 3 ссылок на школы
2026-04-10 04:51:36,657 - INFO - Прогресс - 2320/4212
2026-04-10 04:51:36,658 - INFO - Парсинг района: Mount Vernon Woods,  Sandy Springs
2026-04-10 04:51:41,338 - INFO - Для района Mount Vernon Woods,  Sandy Springs получено 3 ссылок на школы
2026-04-10 04:51:41,339 - INFO - Прогресс - 2321/4212
2026-04-10 04:51:41,340 - INFO - Парсинг района: Commack,  Commack
2026-04-10 04:51:44,406 - INFO - Для района Commack,  Commack получено 3 ссылок на школы
2026-04-10 04:51:44,407 - INFO - Прогресс - 2322/4212
2026-04-10 04:51:44,408 - INFO - Парсинг района: Endion,  Duluth
2026-04-10 04:51:47,640 - INFO - Для района Endion,  Duluth получено 3 ссылок на школы
2026-04-10 04:51:47,641 - INFO - Прогресс - 2323/4212
2026-04-10 04:51:47,642 - INFO - Парсинг района: Latham Park,  Greensboro
2026-04-10 04:51:50,736 - INFO - Для района Latham Park,  Greensboro получено 3 ссылок на школы
2026-04-10 04:51:50,737 - INFO - Прогресс - 2324/4212
2026-04-10 04:51:50,739 - INFO - Парсинг района: College Park,  Indianapolis city (balance)
2026-04-10 04:51:53,812 - INFO - Для района College Park,  Indianapolis city (balance) получено 3 ссылок на школы
2026-04-10 04:51:53,812 - INFO - Прогресс - 2325/4212
2026-04-10 04:51:53,813 - INFO - Парсинг района: East Hill,  Pensacola
2026-04-10 04:51:57,372 - INFO - Для района East Hill,  Pensacola получено 3 ссылок на школы
2026-04-10 04:51:57,373 - INFO - Прогресс - 2326/4212
2026-04-10 04:51:57,374 - INFO - Парсинг района: Sunray West,  North Miami Beach
2026-04-10 04:52:00,620 - INFO - Для района Sunray West,  North Miami Beach получено 3 ссылок на школы
2026-04-10 04:52:00,621 - INFO - Прогресс - 2327/4212
2026-04-10 04:52:00,622 - INFO - Парсинг района: El Portal,  El Portal
2026-04-10 04:52:03,771 - INFO - Для района El Portal,  El Portal получено 3 ссылок на школы
2026-04-10 04:52:03,772 - INFO - Прогресс - 2328/4212
2026-04-10 04:52:03,774 - INFO - Парсинг района: Oaktree,  Levittown
2026-04-10 04:52:06,811 - INFO - Для района Oaktree,  Levittown получено 3 ссылок на школы
2026-04-10 04:52:06,812 - INFO - Прогресс - 2329/4212
2026-04-10 04:52:06,813 - INFO - Парсинг района: Stonebriar,  Frisco
2026-04-10 04:52:09,922 - INFO - Для района Stonebriar,  Frisco получено 3 ссылок на школы
2026-04-10 04:52:09,923 - INFO - Прогресс - 2330/4212
2026-04-10 04:52:09,924 - INFO - Парсинг района: Skyline Terrace,  Midland
2026-04-10 04:52:13,036 - INFO - Для района Skyline Terrace,  Midland получено 3 ссылок на школы
2026-04-10 04:52:13,037 - INFO - Прогресс - 2331/4212
2026-04-10 04:52:13,037 - INFO - Парсинг района: Towne Centre Village,  Mesquite
2026-04-10 04:52:16,125 - INFO - Для района Towne Centre Village,  Mesquite получено 3 ссылок на школы
2026-04-10 04:52:16,126 - INFO - Прогресс - 2332/4212
2026-04-10 04:52:16,128 - INFO - Парсинг района: The Gate District,  St. Louis
2026-04-10 04:52:19,193 - INFO - Для района The Gate District,  St. Louis получено 3 ссылок на школы
2026-04-10 04:52:19,194 - INFO - Прогресс - 2333/4212
2026-04-10 04:52:19,195 - INFO - Парсинг района: Middleton Hills,  Middleton
2026-04-10 04:52:22,258 - INFO - Для района Middleton Hills,  Middleton получено 3 ссылок на школы
2026-04-10 04:52:22,260 - INFO - Прогресс - 2334/4212
2026-04-10 04:52:22,261 - INFO - Парсинг района: Fairview,  Milwaukee
2026-04-10 04:52:25,389 - INFO - Для района Fairview,  Milwaukee получено 3 ссылок на школы
2026-04-10 04:52:25,390 - INFO - Прогресс - 2335/4212
2026-04-10 04:52:25,391 - INFO - Парсинг района: Allen,  Buffalo
2026-04-10 04:52:28,451 - INFO - Для района Allen,  Buffalo получено 3 ссылок на школы
2026-04-10 04:52:28,452 - INFO - Прогресс - 2336/4212
2026-04-10 04:52:28,452 - INFO - Парсинг района: Sunswept,  Pembroke Pines
2026-04-10 04:52:31,509 - INFO - Для района Sunswept,  Pembroke Pines получено 3 ссылок на школы
2026-04-10 04:52:31,510 - INFO - Прогресс - 2337/4212
2026-04-10 04:52:31,510 - INFO - Парсинг района: Plantation,  Miramar
2026-04-10 04:52:34,556 - INFO - Для района Plantation,  Miramar получено 3 ссылок на школы
2026-04-10 04:52:34,557 - INFO - Прогресс - 2338/4212
2026-04-10 04:52:34,558 - INFO - Парсинг района: Danby Corners,  Lexington-Fayette
2026-04-10 04:52:37,895 - INFO - Для района Danby Corners,  Lexington-Fayette получено 3 ссылок на школы
2026-04-10 04:52:37,896 - INFO - Прогресс - 2339/4212
2026-04-10 04:52:37,897 - INFO - Парсинг района: Worthington Park,  Columbus
2026-04-10 04:52:40,989 - INFO - Для района Worthington Park,  Columbus получено 3 ссылок на школы
2026-04-10 04:52:40,990 - INFO - Прогресс - 2340/4212
2026-04-10 04:52:40,991 - INFO - Парсинг района: Whitmer / Trilby,  Toledo
2026-04-10 04:52:44,406 - INFO - Для района Whitmer / Trilby,  Toledo получено 3 ссылок на школы
2026-04-10 04:52:44,407 - INFO - Прогресс - 2341/4212
2026-04-10 04:52:44,407 - INFO - Парсинг района: Sunset Hills,  Lawrence
2026-04-10 04:52:47,503 - INFO - Для района Sunset Hills,  Lawrence получено 3 ссылок на школы
2026-04-10 04:52:47,504 - INFO - Прогресс - 2342/4212
2026-04-10 04:52:47,505 - INFO - Парсинг района: Epping Forest,  Parole
2026-04-10 04:52:48,308 - WARNING - Район не найден: Epping Forest,  Parole
2026-04-10 04:52:48,309 - INFO - Парсинг района: Dunwoodie,  Yonkers
2026-04-10 04:52:51,414 - INFO - Для района Dunwoodie,  Yonkers получено 3 ссылок на школы
2026-04-10 04:52:51,415 - INFO - Прогресс - 2344/4212
2026-04-10 04:52:51,416 - INFO - Парсинг района: Old Howard Beach,  New York
2026-04-10 04:52:54,600 - INFO - Для района Old Howard Beach,  New York получено 3 ссылок на школы
2026-04-10 04:52:54,601 - INFO - Прогресс - 2345/4212
2026-04-10 04:52:54,602 - INFO - Парсинг района: Dry Ridge,  Dry Ridge
2026-04-10 04:52:57,644 - INFO - Для района Dry Ridge,  Dry Ridge получено 3 ссылок на школы
2026-04-10 04:52:57,645 - INFO - Прогресс - 2346/4212
2026-04-10 04:52:57,646 - INFO - Парсинг района: Horse Country,  Kendale Lakes
2026-04-10 04:53:00,760 - INFO - Для района Horse Country,  Kendale Lakes получено 3 ссылок на школы
2026-04-10 04:53:00,761 - INFO - Прогресс - 2347/4212
2026-04-10 04:53:00,762 - INFO - Парсинг района: Blue Ridge Manor,  Blue Ridge Manor
2026-04-10 04:53:03,933 - INFO - Для района Blue Ridge Manor,  Blue Ridge Manor получено 3 ссылок на школы
2026-04-10 04:53:03,934 - INFO - Прогресс - 2348/4212
2026-04-10 04:53:03,935 - INFO - Парсинг района: Edgelawn Randall,  Aurora
2026-04-10 04:53:06,992 - INFO - Для района Edgelawn Randall,  Aurora получено 3 ссылок на школы
2026-04-10 04:53:06,993 - INFO - Прогресс - 2349/4212
2026-04-10 04:53:06,994 - INFO - Парсинг района: Goulds - East,  Goulds
2026-04-10 04:53:10,114 - INFO - Для района Goulds - East,  Goulds получено 3 ссылок на школы
2026-04-10 04:53:10,115 - INFO - Прогресс - 2350/4212
2026-04-10 04:53:10,116 - INFO - Парсинг района: Madisonville,  Cincinnati
2026-04-10 04:53:13,242 - INFO - Для района Madisonville,  Cincinnati получено 3 ссылок на школы
2026-04-10 04:53:13,242 - INFO - Прогресс - 2351/4212
2026-04-10 04:53:13,243 - INFO - Парсинг района: Ritz Carlton,  Jupiter
2026-04-10 04:53:16,324 - INFO - Для района Ritz Carlton,  Jupiter получено 3 ссылок на школы
2026-04-10 04:53:16,325 - INFO - Прогресс - 2352/4212
2026-04-10 04:53:16,326 - INFO - Парсинг района: The 12th Ward,  Racine
2026-04-10 04:53:19,472 - INFO - Для района The 12th Ward,  Racine получено 3 ссылок на школы
2026-04-10 04:53:19,473 - INFO - Прогресс - 2353/4212
2026-04-10 04:53:19,474 - INFO - Парсинг района: North Central,  San Mateo
2026-04-10 04:53:22,523 - INFO - Для района North Central,  San Mateo получено 3 ссылок на школы
2026-04-10 04:53:22,524 - INFO - Прогресс - 2354/4212
2026-04-10 04:53:22,525 - INFO - Парсинг района: Ridgmar,  Fort Worth
2026-04-10 04:53:26,277 - INFO - Для района Ridgmar,  Fort Worth получено 3 ссылок на школы
2026-04-10 04:53:26,278 - INFO - Прогресс - 2355/4212
2026-04-10 04:53:26,279 - INFO - Парсинг района: Savage,  Savage
2026-04-10 04:53:29,922 - INFO - Для района Savage,  Savage получено 3 ссылок на школы
2026-04-10 04:53:29,924 - INFO - Прогресс - 2356/4212
2026-04-10 04:53:29,924 - INFO - Парсинг района: Marty Robbins North,  El Paso
2026-04-10 04:53:33,055 - INFO - Для района Marty Robbins North,  El Paso получено 3 ссылок на школы
2026-04-10 04:53:33,056 - INFO - Прогресс - 2357/4212
2026-04-10 04:53:33,058 - INFO - Парсинг района: Lansingburgh,  Troy
2026-04-10 04:53:36,102 - INFO - Для района Lansingburgh,  Troy получено 3 ссылок на школы
2026-04-10 04:53:36,103 - INFO - Прогресс - 2358/4212
2026-04-10 04:53:36,104 - INFO - Парсинг района: Oak Grove,  Brooklyn Park
2026-04-10 04:53:39,214 - INFO - Для района Oak Grove,  Brooklyn Park получено 3 ссылок на школы
2026-04-10 04:53:39,215 - INFO - Прогресс - 2359/4212
2026-04-10 04:53:39,216 - INFO - Парсинг района: North Beverly,  Beverly
2026-04-10 04:53:42,241 - INFO - Для района North Beverly,  Beverly получено 3 ссылок на школы
2026-04-10 04:53:42,242 - INFO - Прогресс - 2360/4212
2026-04-10 04:53:42,243 - INFO - Парсинг района: Meadowthorpe,  Lexington-Fayette
2026-04-10 04:53:45,377 - INFO - Для района Meadowthorpe,  Lexington-Fayette получено 3 ссылок на школы
2026-04-10 04:53:45,378 - INFO - Прогресс - 2361/4212
2026-04-10 04:53:45,379 - INFO - Парсинг района: Woodland Holt,  Columbus
2026-04-10 04:53:50,530 - INFO - Для района Woodland Holt,  Columbus получено 3 ссылок на школы
2026-04-10 04:53:50,531 - INFO - Прогресс - 2362/4212
2026-04-10 04:53:50,533 - INFO - Парсинг района: Baltimore Highlands,  Baltimore

In [84]:
df_pars = df_pars[~df_pars['links'].isna()].reset_index(drop=True)
df_pars = df_pars[df_pars['links'] != '[]'].reset_index(drop=True)
def link(x):
    return ' ; '.join(x[1:-1].replace("'", '').split(', '))
df_pars['links'] = df_pars['links'].apply(link)
df_pars

,geo_id,neighborhood_city,links
0,9cd7eab982c5c35bcd6f05d732d333c5,"Price End, North Port",https://www.greatschools.org//florida/north-po...
1,b508f5dc4143a48154f0ff995b081678,"The Hills, Coral Springs",https://www.greatschools.org//florida/coral-sp...
2,5b55d57472de1efb82e58cc003f53b78,"Whitesburg Estates, Huntsville",https://www.greatschools.org//alabama/huntsvil...
3,6a62dc1d0f1a59ae0c3de95037e1b683,"Kittyhawk, Dayton",https://www.greatschools.org//ohio/dayton/717-...
4,8f3ec7cc1c199a0a566221bee1aeaa9c,"New Hampstead East, Savannah",https://www.greatschools.org//georgia/savannah...
...,...,...,...
4181,d1e3095ab678803f4b041f4235798872,"Flair, Lauderhill",https://www.greatschools.org//florida/lauderda...
4182,50ebe9038c385b6117d18e557d076841,"Lake Bonny, Lakeland",https://www.greatschools.org//florida/lakeland...
4183,3c969346ea2aa69d1b17362ecb262c76,"Bronx Park, St. Louis Park",https://www.greatschools.org//minnesota/saint-...
4184,a6498e25964d71c4c3834d3f9c4bb11a,"Livingston, New York",https://www.greatschools.org//new-york/geneseo...
4185,748b3444fcd67399ce7da7b6fd003935,"College Hill, Wichita",https://www.greatschools.org//kansas/wichita/1...

In [85]:
df_pars['links'].apply(lambda x: len(x.split(' ; '))).value_counts()

links
3    4145
2      27
1      14
Name: count, dtype: int64

In [86]:
df_pars.to_csv('school_links_by_neighborhoods.csv')